pipeline {
    agent any

    parameters {
        string(name: 'build_version', defaultValue: 'v1.0', description: 'Build version to use for Docker image')
    }

    environment {
        DOCKER_IMAGE = "bjra/demo-java-app:${params.build_version}"
        SONAR_URL = "http://sonarqube:9000"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SaraRifi17/devops-demo-project.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh '''
                cd demo-java-app
                mvn clean package
                '''
            }
        }

        // ⚠️ Désactivé pour éviter crash VM (réactive si besoin)
        /*
        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                    cd demo-java-app
                    mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }
        */

        stage('Build and Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    cd demo-java-app

                    docker build -t $DOCKER_IMAGE .

                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "devops-demo-project"
                GIT_USER_NAME = "SaraRifi17"
            }
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.email "sara.rifi2003@gmail.com"
                    git config user.name "SaraRifi17"

                    git remote set-url origin https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git

                    git fetch origin main

                    git checkout main || git checkout -b main origin/main

                    git pull --rebase origin main

                    sed -i "s/tag:.*/tag: ${build_version}/" helm/app/values.yaml

                    git add helm/app/values.yaml

                    if ! git diff --cached --quiet; then
                        git commit -m "Update deployment image to version ${build_version}"
                        git push origin main
                    else
                        echo "No changes to commit"
                    fi
                    '''
                }
            }
        }
    }
}
